### ISSUE TITLE
Provider plugin crashes

### ISSUE THREAD

**Issue by jdeldvb** [Axual/terraform-provider-axual#54]
Since last week I started having issues with this provider. The plugin crashes on every run. I've tried with different versions of the plugin and it's the same result. I've updated to the lastest version of Terraform and the issue persists.

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-axual_v2.4.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 50 [running]:
axual.com/terraform-provider-axual/internal/provider.(*groupDataSource).Read(0xc00007a3e0, {0x19726f8, 0xc0003762a0}, {{{{0x1976db8, 0xc000376c60}, {0x1737c40, 0xc0003769c0}}, {0x19788f8, 0xc00053e000}}, {{{0x0, ...}, ...}, ...}}, ...)
        axual.com/terraform-provider-axual/internal/provider/data_source_group.go:91 +0x3a5
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0002ba1a0, {0x19726f8, 0xc0003762a0}, 0xc000376330, 0xc0005536c8)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_readdatasource.go:79 +0x433
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0002ba1a0, {0x19726f8?, 0xc000376180?}, 0xc00007a3c0)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_readdatasource.go:55 +0x41c
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0001c65a0, {0x19726f8?, 0xc0004039e0?}, 0xc000428320)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/tf6server/server.go:686 +0x417
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x180fb20?, 0xc0001c65a0}, {0x19726f8, 0xc0004039e0}, 0xc000408280, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000143000, {0x19726f8, 0xc000403950}, {0x1977658, 0xc000007ba0}, 0xc000580c60, 0xc0002ad110, 0x1e60120, 0x0)
        google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000143000, {0x1977658, 0xc000007ba0}, 0xc000580c60)
        google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 11
        google.golang.org/grpc@v1.62.1/server.go:1038 +0x135

Error: The terraform-provider-axual_v2.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by jdeldvb** [comment]
Nevermind, it seems to have been an issue with my lockfile
